# syntax=docker/dockerfile:1
FROM golang:1.22.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ../cmd/rest ./cmd/rest
COPY ../internal ./internal

# -s: strip symbols
# -w: turn off DWARF debug info
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o rest-api ./cmd/rest/main.go

# stage 2
FROM scratch

COPY --from=builder /app/rest-api /rest-api

CMD ["/rest-api"]