# syntax=docker/dockerfile:1
FROM golang:1.22.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ../cmd/cli ./cmd/cli
COPY ../internal ./internal

# -s: strip symbols
# -w: turn off DWARF debug info
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o cli-app ./cmd/cli/main.go

# stage 2
FROM scratch

COPY --from=builder /app/cli-app /cli-app

CMD ["/cli-app"]