# syntax=docker/dockerfile:1
FROM golang:1.22.4-alpine

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ../cmd/rest ./cmd/rest
COPY ../internal ./internal

RUN CGO_ENABLED=0 GOOS=linux go build -o rest-api ./cmd/rest/main.go

EXPOSE 9172

CMD ["./rest-api"]